services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network

  client:
    build:
      context: ./client
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
